### ISSUE TITLE
quickbar management and data backup

### ISSUE THREAD

**Issue by xMassimo** [simon387/daocstarter#10]
user.dat and .ini files backup to prevent data loss (sometimes user.dat corrupts someway)
option to make a .ini file the default (button to apply it on a char, useful on new chars)
more to come.

**Comment by simon387** [comment]
![schermata da 2017-06-08 11-49-10](https://user-images.githubusercontent.com/18740246/26922934-f282cb12-4c40-11e7-9460-fe21b6c0c80c.png)

**Comment by xMassimo** [comment]
adesso pensavo che quando faccio un pg nuovo, non sempre lo giocherei alla stessa risoluzione, quindi servirebbero dei templates diversi per ogni risoluzione a cui gioco (due, una risoluzione per i macro teams e una per i pg che gioco in rvr) quindi la funzione che applica un template di default dovrebbe darti la scelta di pescare in una cartella quale scegliere e poi applicare, non solamente ereditarlo dal character che stai editando. quindi ricapitolando:
-pulsante che crea un template usando l'ini del char che editi con prompt per il salvataggio del file nella cartella dedicata.
-pulsante che carica un template tra quelli salvati nella cartella dedicata. questo pulsante possibilmente dovrebbe mostrarti la scelta che è stata caricata.
-pulsante che applica il template.
