### ISSUE TITLE
Semi-automatic UI scaler

### ISSUE THREAD

**Issue by xMassimo** [simon387/daocstarter#11]
avrei in mente anche una funzione più avanzata per scalare la UI alla risoluzione, che automatizzerebbe ciò che già faccio a mano.
poniamo che abbia un pg che voglio loggare sia a 1280x720 sia a 2560x1440.
ora io ho due templates vuoti (senza barre) con la posizione degli oggetti della mia UI, dimensione font della chat ecc, basati sulle due risoluzioni (tp1, tp2)
**le fasi della mia procedura manuale:**
1- apro il .ini con le barre attuali, copio le righe che contengono le informazioni su barre, macro e qbinds. quelle da [Quickbar] (incluso) a [Chat] (escluso) e da [QuickBinds] (incluso) a [Househelp] (escluso).
2- apro una copia di tp1 o di tp2 (a seconda della risoluzione che mi serve), incollo le righe nella posizione che gli spettano.
3- rinomino il .ini originale in [nome]-[server]-[risoluzione1].ini
4- rinomino il tp1/tp2 in [nome]-[server].ini
5- faccio un backup di (4) e lo rinomino in [nome-][server]-[risoluzione2]
ora mi ritrovo con entrambi i backup alle risoluzioni che mi servono pronti per essere rinominati ed usati
**la procedura automatica che ho pensato.**
prerequisiti:
a- presenza del .ini originale da cui prendere le barre
b- presenza di entrambi tp1/tp2 (o anche di più per chi gioca ad un numero diverso di risoluzioni) che contengono i templates alle varie risoluzioni.
fasi:
1- il software identifica la risoluzione a cui il client viene lanciato
2- apre il .ini con le barre attuali, copia le righe che contengono le informazioni su barre, macro e qbinds. quelle da [Quickbar] (incluso) a [Chat] (escluso) e da [QuickBinds] (incluso) a [Househelp] (escluso).
3- apre una copia di tp1 o di tp2 (a seconda della risoluzione che mi serve), incolla le righe nella posizione che gli spettano.
4- rinomina il .ini originale in .ini.bak
5- rinomina il nuovo file in [nome]-[server].ini
6- se tutto ha funzionato elimina il .ini.bak
7- lancia il client

con questa procedura è sempre garantita la sopravvivenza di qbar, macro, qbinds perché vengono ereditate nell'ultimo file.
i vari tp1/tp2 ecc possono anche essere quelli di default che contengono già altre barre (ad esempio io per i nuovi chars ho templates con macro /anon, /statsanon, /gc quit, /autosplit c, e cose simili. la presenza di questi elementi non sarebbe rilevante visto che verrebbero comunque sostituiti.

**Comment by xMassimo** [comment]
avevo pensato anche ad uno scaler veramente automatico che andasse a modificare i vari parametri della posizione degli elementi della UI, font size e via dicendo ma richiederebbe un lavoro immane di ricerca. che facciano loro una ui vettoriale. avrebbe anche il limite che ogni UI custom è diversa e non tutti usano quella base.

**Comment by xMassimo** [comment]
sarebbe opportuna la presenza nelle opzioni di un check per abilitare esplicitamente questa funzione dove si possano anche caricare i vari tp1 tp2 ecc. anche il #10 dovrebbe beneficiare dell'indicazione di tp1, tp2, tpn con n = al numero delle risoluzioni disponibili, con libertà ovviamente di caricare solo quelle che sono necessarie.

**Comment by simon387** [comment]
troppo basti e non lo userebbe nessuno, per ora teniamo il https://github.com/simon387/daocstarter/issues/10
