### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by jd-wheaton** [simon387/daocstarter#16]
Hi! do you have already performed a [cursory search](https://github.com/simon387/daocstarter/issues?utf8=✓&q=is%3Aissue+) to see if a similar issue has already been submitted?

if yes, please enter the following informations!

* The version of daocstarter you are using

3.8.4
* The operating system you are using

Win 10 x64 Enterprise 1809

* If applicable, what you were doing when the issue arose and what you expected to happen

Initial launch of application after packaging and building electron installer package per documentation

* Screenshots and animated GIFs

See below
* Error output that appears in your terminal, dev tools or as an alert

![daocstarter-err](https://user-images.githubusercontent.com/14035228/47050840-d6325d00-d16f-11e8-9245-4a4742493ca0.png)

* Explanation of the issue

I do admit I've never packaged an Electron application nor have I built an installer from package. But I followed documentation and have this error upon launch. I can build and run the application in VSCode with out any issues.

**Comment by simon387** [comment]
hello!

my bad, just go in the ```package.json``` and add the ini dependency under ```"dependency":```

```,"ini": "^1.3.5"```

you can remove also it from ```devDepenecies```

and re-run the command, something like

```electron-packager . daocstarter --platform win32 --arch x64 --out dist --icon=img\i.ico --overwrite```

This should fix the error (did on mine machine)

**Comment by simon387** [comment]
I fixed it here

33bb8fe

**Comment by simon387** [comment]
if you have not changed anything you can just delete all the project folder and clone it again

or type ```git pull``` to upgrade the project

**Comment by simon387** [comment]
welcome to github, I love it

**Comment by jd-wheaton** [comment]
Found a caveat to this original err, each time the application started with the error, a background daocstarter app did not close, so I had 7-8 copies running that I was unaware of that needed to be manually terminated before I could delete the dist directory and rebuild/repackage the application. Just a heads up.

**Comment by simon387** [comment]
> Found a caveat to this original err, each time the application started with the error, a background daocstarter app did not close, so I had 7-8 copies running that I was unaware of that needed to be manually terminated before I could delete the dist directory and rebuild/repackage the application. Just a heads up.

yeah i know, there is an issue and the app termination I suppose... 

it depends on the build

maybe ill fix that too

**Comment by jd-wheaton** [comment]
Your fix solved this issue. Case closed, great work and thank you for such a quick turn around! Great app. Much better than Mojo. If you added a way to adjust gamma that would be fantastic.

**Comment by simon387** [comment]
Thank you! And it's open source, anyone can edit it... there is the gamma correction option, if you download the latest release you can use it.

The problem with this app is that I don't play daoc anymore so I stopped to add functions to it 😥

**Comment by jd-wheaton** [comment]
You should come back to game once 1.125 update is released. They are making a lot of positive changes and you can check them out on Pendragon the test server.

**Comment by jd-wheaton** [comment]
Also - where do I find the CALGamma tool? I see it in the drop down menu but I don't have nor can I find an app online called CALGamma.

**Comment by simon387** [comment]
to have it enabled from source (so without downloading a .exe release) you need to compile it with autoit scripting language...

**Comment by jd-wheaton** [comment]
Where do I find some instructions on how to compile it with autoit?
