### ISSUE TITLE
Unhandled Rejection Error - Autoit compiling

### ISSUE THREAD

**Issue by jd-wheaton** [simon387/daocstarter#17]
Hi! do you have already performed a [cursory search](https://github.com/simon387/daocstarter/issues?utf8=✓&q=is%3Aissue+) to see if a similar issue has already been submitted?

if yes, please enter the following informations!

* The version of daocstarter you are using

Latest
* The operating system you are using

Win 10 x64 Enterprise
* If applicable, what you were doing when the issue arose and what you expected to happen

Installed Autoit language, adjusted paths in .\autoit\autoit-compile.js, ran node .\autoit\autoit-compile.js. Expected script to run without errors, but encountered two Unhandled Rejection Errors and a message unable to find 'dist.zip'
* Screenshots and animated GIFs

See below
* Error output that appears in your terminal, dev tools or as an alert

![daocstarter-err-autoit](https://user-images.githubusercontent.com/14035228/47109349-06cfd080-d21c-11e8-810d-c692a8930a3f.png)

* Explanation of the issue

Cannot find 'dist.zip' and 2 Unhandled Rejection Errors. See output.

**Comment by simon387** [comment]
now I can't check it because I don't have a machine with Windows installed, but I will do it in the next days

looks like a bad configuration error in the autoit compiling mechanism

**Comment by jd-wheaton** [comment]
I love Code, it's a great Electron application for sure. I've look at the source code and I tell you an army of Microsoft PhD employees and some of the best JS developers on the Internet have contributed to it. I am so totally lost looking at it, it almost doesn't look at all like JS.

**Comment by jd-wheaton** [comment]
I will try to debug this myself. I would also not be against you looking at it on a VM off my machine.

**Comment by simon387** [comment]
+ fixed that error (was duo to an old version of nodejs, I suppose)
+ added more details on how to build on ```readme.md```
+ not fully tested on windows :(

**Comment by simon387** [comment]
tested on windows in a new PC, it works and builded the new exe 3.8.7
