### ISSUE TITLE
DAoC Starter Resolution dropdown

### ISSUE THREAD

**Issue by TheBloodcore** [simon387/daocstarter#2]
I cant seem to add an account, because i cant activate the resolution dropdown, i click it and nothing happens. I tried running the program as admin.

I have included a picture of the problem.

My OS is Windows 10 pro, Geforce 950.
![udklip](https://cloud.githubusercontent.com/assets/28455992/25760133/a593aacc-31d5-11e7-9dfa-4a75907cc97f.PNG)

**Comment by simon387** [comment]
even with the 1.4.2 version?

if the console from the dev tools is blank, give me this info:

+ open Windows PowerShell (<kbd>win</kbd> + <kbd>r </kbd> and run the command: <code>powershell</code>)
+ type: <code>get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,
VerticalResolution -descending | select HorizontalResolution, VerticalResolution</code>
+ paste me the output!
e.g. I got this from my Windows 10 64 PC GeForce 670 382.05: ![alt tag](http://www.simonecelia.it/github/img/powershell.png)
+ if you don't get a similar list, just send me the full information with <code>get-wmiobject -query "select * from CIM_VideoControllerResolution"</code>

Thank you for your report!

**Comment by TheBloodcore** [comment]
Hi, tyvm for the reply!


When i input


"get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,

VerticalResolution -descending | select HorizontalResolution, VerticalResolution"

Without the "" in the powershell command, i get no output, theres a chance im doing something wrong, but i have attached a screenshot for you to see.

I tried inputting it a few times, thats why it shows that many times, sorry for that.

Best regards.

[cid:9b271d99-ce9d-4062-992f-c047661cc725]

________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 01:21:10
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


even with the 1.4.2 version?

if the console from the dev tools is blank, give me this info:

  *   open Windows PowerShell (win + r and run the command: powershell)
  *   type: get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,
VerticalResolution -descending | select HorizontalResolution, VerticalResolution
  *   paste me the output!
e.g. I got this from my Windows 10 64 PC GeForce 670 382.05: [alt tag] <https://camo.githubusercontent.com/06748cd471a99691311f997a112162cebffd1cc6/687474703a2f2f7777772e73696d6f6e6563656c69612e69742f6769746875622f696d672f706f7765727368656c6c2e706e67>
  *   if you don't get a similar list, just send me the full information with get-wmiobject -query "select * from CIM_VideoControllerResolution"

Thank you for your report!

**Comment by simon387** [comment]
sorry but I can't see any attachment!

**Comment by TheBloodcore** [comment]
Oops, i didnt read the last line, very sorry for this, i always try to be detailed when i repport bugs, but htat last line, i didnt see.



However it didnt give any output, i might be me doing something wrong.


Since the last mail i have updated my graphics driver to 382.05 im running daoc starter 142


Pic attached here:


[cid:eee010d4-cb42-4305-97d3-93afb8a34aa7]nt see.




________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 01:21:10
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


even with the 1.4.2 version?

if the console from the dev tools is blank, give me this info:

  *   open Windows PowerShell (win + r and run the command: powershell)
  *   type: get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,
VerticalResolution -descending | select HorizontalResolution, VerticalResolution
  *   paste me the output!
e.g. I got this from my Windows 10 64 PC GeForce 670 382.05: [alt tag] <https://camo.githubusercontent.com/06748cd471a99691311f997a112162cebffd1cc6/687474703a2f2f7777772e73696d6f6e6563656c69612e69742f6769746875622f696d672f706f7765727368656c6c2e706e67>
  *   if you don't get a similar list, just send me the full information with get-wmiobject -query "select * from CIM_VideoControllerResolution"

Thank you for your report!

**Comment by TheBloodcore** [comment]
I will redo both, just a sec.

________________________________
Fra: Blood Core <bloodcore@outlook.com>
Sendt: 6. maj 2017 01:39:16
Til: simon387/daocstarter
Emne: Sv: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


Oops, i didnt read the last line, very sorry for this, i always try to be detailed when i repport bugs, but htat last line, i didnt see.



However it didnt give any output, i might be me doing something wrong.


Since the last mail i have updated my graphics driver to 382.05 im running daoc starter 142


Pic attached here:


[cid:eee010d4-cb42-4305-97d3-93afb8a34aa7]nt see.




________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 01:21:10
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


even with the 1.4.2 version?

if the console from the dev tools is blank, give me this info:

  *   open Windows PowerShell (win + r and run the command: powershell)
  *   type: get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,
VerticalResolution -descending | select HorizontalResolution, VerticalResolution
  *   paste me the output!
e.g. I got this from my Windows 10 64 PC GeForce 670 382.05: [alt tag] <https://camo.githubusercontent.com/06748cd471a99691311f997a112162cebffd1cc6/687474703a2f2f7777772e73696d6f6e6563656c69612e69742f6769746875622f696d672f706f7765727368656c6c2e706e67>
  *   if you don't get a similar list, just send me the full information with get-wmiobject -query "select * from CIM_VideoControllerResolution"

Thank you for your report!

**Comment by TheBloodcore** [comment]
Is this better?

________________________________
Fra: Blood Core <bloodcore@outlook.com>
Sendt: 6. maj 2017 01:40:33
Til: simon387/daocstarter
Emne: Sv: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


I will redo both, just a sec.

________________________________
Fra: Blood Core <bloodcore@outlook.com>
Sendt: 6. maj 2017 01:39:16
Til: simon387/daocstarter
Emne: Sv: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


Oops, i didnt read the last line, very sorry for this, i always try to be detailed when i repport bugs, but htat last line, i didnt see.



However it didnt give any output, i might be me doing something wrong.


Since the last mail i have updated my graphics driver to 382.05 im running daoc starter 142


Pic attached here:


[cid:eee010d4-cb42-4305-97d3-93afb8a34aa7]nt see.




________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 01:21:10
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


even with the 1.4.2 version?

if the console from the dev tools is blank, give me this info:

  *   open Windows PowerShell (win + r and run the command: powershell)
  *   type: get-wmiobject -query "select HorizontalResolution, VerticalResolution from CIM_VideoControllerResolution" | Sort-Object HorizontalResolution,
VerticalResolution -descending | select HorizontalResolution, VerticalResolution
  *   paste me the output!
e.g. I got this from my Windows 10 64 PC GeForce 670 382.05: [alt tag] <https://camo.githubusercontent.com/06748cd471a99691311f997a112162cebffd1cc6/687474703a2f2f7777772e73696d6f6e6563656c69612e69742f6769746875622f696d672f706f7765727368656c6c2e706e67>
  *   if you don't get a similar list, just send me the full information with get-wmiobject -query "select * from CIM_VideoControllerResolution"

Thank you for your report!

**Comment by simon387** [comment]
sorry but I don't see any screenshot! 

![alt tag](http://www.simonecelia.it/github/img/noscreen.png)

But I am assuming you get no output from that command, so I' am writing the 1.4.3 with a new workaround  attempt...

**Comment by TheBloodcore** [comment]
Oh okay, im using a hotmail to write you from.


But yes, im not getting any output from the two commands, and the dropdown box from the daoc starter program doesnt drop down.


Anyway.


I want to express my gratitude, that you are working on a program like this. I think we all liked Mojo, but no one is updating it anymore, and BS messed with some of its features, like borderles windows, and team launches.


So this program, daoc starter, could be very good for the whole community.


A few brainstorm ideas:


I wrote a couple of sugestions on postcount under the name Bloodcore, i wrote that Mojo had a spellcrafting feature, where you could flag a char as spellcrafter, then in the spellcrafting menu, (in mojo) chose this crafter and its realm, and import builds (they had to have gem names) and that would allow Mojo to put the gems on the quickbars ingame for you, this is a really awesome feature, and ive used it many times, because not only does it save time, its safer too, becuase you cant acidently put a wrong gem on the bar. So if in the future this could be in daoc starter, that would be awesome.


A checkbox for "window name, the same as toon name" would be awesome.


Mojo also had these fixes for ATI/AMD graphic cards, im not 100% sure what they did, but it seemed they worked for some people.


Anyway, this is just me brainstorming, im not playing alot of daoc these days, but im still very excited that this program is being made.


So tyvm for doing this.

________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 01:52:03
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


sorry but I don't see any screenshot!

[alt tag]<https://camo.githubusercontent.com/6572caac970719fe330a98f49d2a6c704edbd746/687474703a2f2f7777772e73696d6f6e6563656c69612e69742f6769746875622f696d672f6e6f73637265656e2e706e67>

But I am assuming you get no output from that command, so I' am writing the 1.4.3 with a new workaround attempt...

**Comment by simon387** [comment]
released the 1.4.3 https://github.com/simon387/daocstarter/releases/tag/v1.4.3

So you can enter any resolution stored in the setting section...

For now it is a temporary solution...

Thank you for your appreciation,
I wrote various "daocstarter" before the Mojo software but never released in public.

In my opinion this project could be better on helping the very old DAoC community because I made it opensource! so everyone can edit it and the code never dies! (I wish the DAoC client could be free too, there are so many bugs and no graphic improvements!)

In my free time I am going to add features like the ones you suggested.

Thank you again

**Comment by TheBloodcore** [comment]
That totally worked!


Im very impressed with this software already, only things it needs really in this early stage, is import chars from the LOTM folder like mojo had it, so you dont have to input the information manually, maybe a better way to create teams, even though the checkbox select at the top of the screen, is working fine as it is now, where i just have 3 chars/3 accounts added. But i have like 120 chars, and with all of them added, it would be a bit messy, maybe a "teams" section, between characters, and accounts, idk.


On windows 10, does it create a shortcut in the start menu at all? I just opened the program from somewhere in the %appdata% folder i think, and pinned it to my processbar, a shortcut would probalbly be good (unless its already there and i didnt see it)


This is really great, i had a whole thread about mojo, and how BS shouldnt not mess with features that was in mojo (they did so the borderless windows didnt work) beib told me they could not patch around these things, if they had to implement something, and it broke mojo, that was basicly too bad, and i do understand her, but having a program like daoc starter now here, is just making me glad.


TY again.

________________________________
Fra: simone <notifications@github.com>
Sendt: 6. maj 2017 02:21:01
Til: simon387/daocstarter
Cc: TheBloodcore; Author
Emne: Re: [simon387/daocstarter] DAoC Starter Resolution dropdown (#2)


released the 1.4.3 https://github.com/simon387/daocstarter/releases/tag/v1.4.3

So you can enter any resolution stored in the setting section...

For now it is a temporary solution...

Thank you for your appreciation,
I wrote various "daocstarter" before the Mojo software but never released in public.

In my opinion this project could be better on helping the very old DAoC community because I made it opensource! so everyone can edit it and the code never dies! (I wish the DAoC client could be free too, there are so many bugs and no graphic improvements!)

In my free time I am going to add features like the ones you suggested.

Thank you again
