### ISSUE TITLE
Bug in 1.5.0. while launching teams

### ISSUE THREAD

**Issue by TheBloodcore** [simon387/daocstarter#3]
Hi guys!

First off, tyvm for adding the advanced team launch, its highly appreciated.

I created a 3 char team, and when i launch it, i got this popup error "TypeError: Cannot read property 'split' of undefined"
![udklip](https://cloud.githubusercontent.com/assets/28455992/26303565/58840d9c-3ee8-11e7-8261-057a15ed31f3.PNG)

Image attached.

One acount would launch like it should, but after that one the next would lanch in full screen, and the third account would not load, as "i already run two instances" After this while doing nothing to the daocstarter, i was able to launch the 3 accounts, one by one.

**Comment by simon387** [comment]
hi and ty for your report

I suspect this is duo to the multimonitor setup.

Will be fixed soon

**Comment by TheBloodcore** [comment]
Hi!

Yes im indeed using a multimonitor setup

TY for looking at it, i appreciate it!

**Comment by simon387** [comment]
I don't have a multimonitor setup but a friend of mine tried out it and it worked.

Are you sure that any character you have got the resolution dropdown populated?

**Comment by TheBloodcore** [comment]
All the characters in the team has full HD resolution 1920x1080 from the dropdown, windowed and borderless checked.

I tried creating another team, with some of the same, and some different characters, it it did infact launch, but not past the 2 accounts, even though i had clicked "remove clients limiter" and have run the program as administrator.

I then delted the first team that had the original error, and readded it, and it did infact launch (no idea what i did diferently) but again not past 2 accounts.

**Comment by simon387** [comment]
you _must_ run as administrator to run more then 2 accounts. 

So you are telling me that you can't log more then 2 accounts at the same time?

**Comment by TheBloodcore** [comment]
I have gone into settings of the program, to compatility, and checked "always run this program as administrator"

If i run 3 accounts from the favorites, and start them 1 by 1, i can run 3 accounts, but when i try to launch a team, with the same 3 characters i get the error, that i can only run 2 instances at the time, im not sure if its just me being a newbie, but i think i got it right, with running as admin. All this from the same session of daoc starter.

**Comment by simon387** [comment]
maybe you need  a larger deelay amounts (millsecs)...  may I ask you your PC specs (manly ram and processor)

**Comment by TheBloodcore** [comment]
My CPU is a Intel 4770k running at stock speed. 3.5 GHZ, i have 16 GB of Ram, i run windows and my games from two seperate SDD's. My gfx is only a Geforce 950 though.

In the team launch the first account is fully loaded when the second starts to load, and the second account is fully loaded when the third gives the two instances error.

**Comment by simon387** [comment]
your specs are very good, I dunno why you got this problem, this is not due to the multimonitor setup.

Are you able to run this program? https://technet.microsoft.com/en-us/sysinternals/handle.aspx

is the piece of software I use to run more accounts at the same time (and I think Mojo does the same)

**Comment by TheBloodcore** [comment]
I havent seen the original error i posted, since i deleted the team and readded it, so thats good.

Mojo does the same yes, but only with clients launched through mojo.

I've no idea how the handle program works.

We will have to see if its just me who has this problem, it might be, though i have no clue of why that is.

I have no problems launching the accounts 1 by 1.

TY for taking the time, i aprreciate it!

IDK if you want me to close the ticket after this, but ill leave that up to you.

**Comment by simon387** [comment]
Let it open, maybe we'll solve it or someone will help! my friend and I still testing it
