### ISSUE TITLE
search form

### ISSUE THREAD

**Issue by xMassimo** [simon387/daocstarter#6]
increase search form size and move it to the center

**Comment by xMassimo** [comment]
top feature, make it BIG, make it easily visible!

**Comment by simon387** [comment]
invertendo di posizione il numero di entry con il search ti andrebbe bene lo stesso?
 

![schermata da 2017-06-07 14-33-02](https://user-images.githubusercontent.com/18740246/26880483-de174646-4b94-11e7-9ddf-c7301c5d25f4.png)

**Comment by xMassimo** [comment]
sicuramente in questo modo è molto più visibile e comodo
